# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 FirebaseSDKVersion = '10.7.0'
target 'MyPill' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  # Pods for MyPill

  target 'MyPillTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
pod 'Firebase/Firestore'

  end

end
